services:
  verdaccio:
    build:
      context: ./docker/verdaccio
    container_name: verdaccio
    volumes:
      - verdaccio-storage:/verdaccio/storage
    networks:
      - cd-network

  ssh-target:
    build:
      context: ./docker/ssh-target
    container_name: ssh-target
    networks:
      - cd-network
    depends_on:
      - verdaccio

networks:
  cd-network:
    driver: bridge

volumes:
  verdaccio-storage:
